services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - es01
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    command: >
      sh -c "until curl -s http://es01:9200; do echo 'Waiting for Elasticsearch...'; sleep 5; done && npm install --build-from-source && npm run start"


  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000" # Map frontend to localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules # Avoid mounting if node_modules should persist in container
    working_dir: /app
    command: >
      sh -c "npm install && npm start"
    networks:
      - app-network

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=elastic@123
    ports:
      - "9201:9200"
      - "9300:9300"
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10

networks:
  app-network:
    driver: bridge
