const CONSTANTS = {
    ENTERING_TO: 'ENTERING TO',
    BUSINESS_LOGIC: 'BUSINESS LOGIC',
    CONTROLLER: 'CONTROLLER',
    SERVICE_METHOD: 'SERVICE_METHOD',
    STATUS_CODE:{
        SUCCESS: 200,
        INTERNAL_SERVER_ERROR: 500,
        FAILURE: 502,
        RETRY_ERROR : 405,
        DATABASE_ERROR: 510,
        UNAUTHORISED: 401,
        NOT_FOUND: 404
    },
    ERROR_CODE:{
        INCORRECT_PASSWORD: 'IP0001',
        PASSWORD_MISMATCH: 'PM0001',
        EMAIL_PASSWORD_MISSING: 'EPM001',
        USER_EXIST: 'UE0001', //please login
        REGISTRATION_FAILED: 'RF0001',
        USER_NOT_FOUND: 'UNF001',
        OAUTH_DONE: 'OAD001',
        OAUTH_NOT_DONE: 'OAN001',
        USER_CREATED: 'UC0001'
    }
}

module.exports = CONSTANTS;
